/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function new_vec(): number;
export function new_vec_with_capacity(a: number): number;
export function vec_from_iter(a: number, b: number): number;
export function push(a: number, b: number): void;
export function pop(a: number): number;
export function vec_at(a: number, b: number): number;
export function vec_len(a: number): number;
export function vec_capacity(a: number): number;
export function vec_index(a: number, b: number): number;
export function vec_set(a: number, b: number, c: number): void;
export function vec_splice(a: number, b: number, c: number, d: number, e: number): number;
export function vec_split_off(a: number, b: number): number;
export function vec_append(a: number, b: number): void;
export function vec_empty(a: number): void;
export function vec_insert(a: number, b: number, c: number): void;
export function vec_remove(a: number, b: number): number;
export function vec_shrink_to(a: number, b: number): void;
export function vec_swap(a: number, b: number, c: number): void;
export function vec_swap_remove(a: number, b: number): void;
export function drop_vec(a: number): void;
export function spawn_thread(a: number, b: number, c: number): number;
export function available_parallelism(): number;
export function current_thread(): number;
export function thread_panicking(): number;
export function park_thread(): void;
export function park_thread_with_timeout(a: number): void;
export function sleep(a: number): void;
export function yield_now(): void;
export function is_finished(a: number): number;
export function thread(a: number): number;
export function join(a: number): void;
export function thread_id(a: number): number;
export function thread_name(a: number, b: number): void;
export function drop_thread(a: number): void;
export function drop_join_handle(a: number): void;
export function thread_unpark(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
